### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by aediot** [rhiever/TwitterFollowBot#116]
Hello, 

When trying to run the Twitter bot I get the error below:

[aediot@server TwitterFollowBot]$ python yourscript.py 
Traceback (most recent call last):
  File "yourscript.py", line 4, in <module>
    my_bot = TwitterBot()
  File "/usr/lib/python3.5/site-packages/TwitterFollowBot/__init__.py", line 42, in __init__
    self.bot_setup(config_file)
  File "/usr/lib/python3.5/site-packages/TwitterFollowBot/__init__.py", line 82, in bot_setup
    value = line[1].strip()
IndexError: list index out of range

Here is my yourscript.py:

from TwitterFollowBot import TwitterBot

my_bot = TwitterBot()

my_bot.auto_fav("test", count=1000)
my_bot.auto_follow_followers()
my_bot.auto_unfollow_nonfollowers()

And here is my config.txt in the same directory:

OAUTH_TOKEN:7example
OAUTH_SECRET:example
CONSUMER_KEY:example
CONSUMER_SECRET:example
TWITTER_HANDLE:delevrything
ALREADY_FOLLOWED_FILE:already-followed.txt
FOLLOWERS_FILE:followers.txt
FOLLOWS_FILE:following.txt
USERS_KEEP_FOLLOWING:
USERS_KEEP_UNMUTED:
USERS_KEEP_MUTED:
FOLLOW_BACKOFF_MIN_SECONDS:10
FOLLOW_BACKOFF_MAX_SECONDS:60

**Comment by tunnelsup** [comment]
Check your config.txt file for extra whitespaces. Even an extra new line at the end can cause this problem.

This is a duplicate of issue https://github.com/rhiever/TwitterFollowBot/issues/82
