### ISSUE TITLE
my_bot = TwitterBot, my_bot = TwitterBot() problem

### ISSUE THREAD

**Issue by LeoKolade** [rhiever/TwitterFollowBot#126]
hello i'm really confused here as im VERY NEW to programming. Any time i post my_bot = TwitterBot , it seems to work but then the next command i put in my_bot.send_tweet("Hello People") give me this TypeError: unbound menthod send_tweet() must be called with TwitterBot instance as first argument (got str instance instead)

if i use my_bot = TwitterBot() 
it gives me 
>>> my_bot = TwitterBot()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\TwitterFollowBot\__init__.py", line 42, in
 __init__
    self.bot_setup(config_file)
  File "C:\Python27\lib\site-packages\TwitterFollowBot\__init__.py", line 78, in
 bot_setup
    with open(config_file, "r") as in_file:
IOError: [Errno 2] No such file or directory: 'config.txt'

i am soooo confused please help

**Comment by chemostafa** [comment]
Whene you open :

cd TwitterFollowBot

Did you see file named config.txt ?

Any way I like you new in the programming but
