### ISSUE TITLE
Hello help me this problem not starting tweet bot

### ISSUE THREAD

**Issue by Killed596** [rhiever/TwitterFollowBot#153]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/twitter/api.py", line 315, in _handle_response
    handle = urllib_request.urlopen(req, **kwargs)
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/TwitterFollowBot/tweet.py", line 8, in <module>
    my_bot.sync_follows()
  File "/usr/local/lib/python3.9/dist-packages/TwitterFollowBot/__init__.py", line 148, in sync_follows
    followers_status = self.TWITTER_CONNECTION.followers.ids(screen_name=self.BOT_CONFIG["TWITTER_HANDLE"])
  File "/usr/local/lib/python3.9/dist-packages/twitter/api.py", line 308, in __call__
    return self._handle_response(req, uri, arg_data, _timeout)
  File "/usr/local/lib/python3.9/dist-packages/twitter/api.py", line 341, in _handle_response

**Comment by Killed596** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/twitter/api.py", line 315, in _handle_response
    handle = urllib_request.urlopen(req, **kwargs)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tweet.py", line 8, in <module>
    my_bot.sync_follows()
  File "/usr/local/lib/python3.8/dist-packages/TwitterFollowBot/__init__.py", line 148, in sync_follows
    followers_status = self.TWITTER_CONNECTION.followers.ids(screen_name=self.BOT_CONFIG["TWITTER_HANDLE"])
  File "/usr/local/lib/python3.8/dist-packages/twitter/api.py", line 308, in __call__
    return self._handle_response(req, uri, arg_data, _timeout)
  File "/usr/local/lib/python3.8/dist-packages/twitter/api.py", line 341, in _handle_response
    raise TwitterHTTPError(e, uri, self.format, arg_data)


how to fix this problem ?
