### ISSUE TITLE
Error: value = line[1].strip() IndexError: list index out of range

### ISSUE THREAD

**Issue by bysanlulls** [rhiever/TwitterFollowBot#84]
Trying to run the bot, I get the error: 
C:\Python34\python.exe D:/TwitterFollowBot-master/bot.py
Traceback (most recent call last):
  File "D:/TwitterFollowBot-master/bot.py", line 3, in <module>
    my_bot = TwitterBot('D:\TwitterFollowBot-master/config.txt')
  File "D:\TwitterFollowBot-master\TwitterFollowBot\__init__.py", line 42, in __init__
    self.bot_setup(config_file)
  File "D:\TwitterFollowBot-master\TwitterFollowBot\__init__.py", line 82, in bot_setup
    value = line[1].strip()
IndexError: list index out of range

**Comment by rhiever** [comment]
Your config.txt isn't set up correctly. Please see, e.g., #82
